language: ruby
rvm:
  - 2.2.2
env:
  - RAILS_ENV=test
services:
  - postgresql
before_script:
  - psql -c 'create database tepoztecatl_test;' -U postgres
script:
  - rails db:migrate
  - bundle exec rspec