language: ruby
rvm:
  - 2.5.3
env:
  - RAILS_ENV=test
install:
  - bundle install --jobs=3 --retry=3
services:
  - postgresql
before_script:
  - psql -c 'create database tepoztecatl_test;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - rails db:migrate
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
